-- Keybinding labels (must use global strings with exact binding names)
BINDING_HEADER_BARSMITH = "BarSmith"
_G["BINDING_NAME_CLICK BarSmithModule_questItems:LeftButton"] = "BarSmith Quest Items"
_G["BINDING_NAME_CLICK BarSmithModule_consumables:LeftButton"] = "BarSmith Consumables"
_G["BINDING_NAME_CLICK BarSmithModule_consumables_potions:LeftButton"] = "BarSmith Potions (All)"
_G["BINDING_NAME_CLICK BarSmithModule_consumables_flask:LeftButton"] = "BarSmith Flasks / Elixirs"
_G["BINDING_NAME_CLICK BarSmithModule_consumables_food:LeftButton"] = "BarSmith Food / Drink"
_G["BINDING_NAME_CLICK BarSmithModule_consumables_bandage:LeftButton"] = "BarSmith Bandages"
_G["BINDING_NAME_CLICK BarSmithModule_consumables_utility:LeftButton"] = "BarSmith Utilities"
_G["BINDING_NAME_CLICK BarSmithModule_trinkets:LeftButton"] = "BarSmith Trinkets"
_G["BINDING_NAME_CLICK BarSmithModule_classSpells:LeftButton"] = "BarSmith Class Spells"
_G["BINDING_NAME_CLICK BarSmithModule_professions:LeftButton"] = "BarSmith Professions"
_G["BINDING_NAME_CLICK BarSmithModule_mounts:LeftButton"] = "BarSmith Mounts"
_G["BINDING_NAME_CLICK BarSmithModule_hearthstones:LeftButton"] = "BarSmith Hearthstones"
_G["BINDING_NAME_CLICK BarSmithModule_macros:LeftButton"] = "BarSmith Macros"
